- name: Create Hypervisor Linux bridges
  template:
    src: "{{ item.origin }}"
    dest: /etc/sysconfig/network-scripts/{{ item.file }}
  with_items:
    - { origin: 'ifcfg-br-access.j2', file: 'ifcfg-br-access'}
    - { origin: 'ifcfg-br-provisioning.j2', file: 'ifcfg-br-provisioning'}
    - { origin: 'ifcfg-em1.j2', file: 'ifcfg-em1'}
    - { origin: 'ifcfg-em2.10.j2', file: 'ifcfg-em2.10'}
    - { origin: 'ifcfg-em2.j2', file: 'ifcfg-em2'}
    - { origin: 'ifcfg-ifcfg-br-trunk.j2', file: 'ifcfg-ifcfg-br-trunk'}

- name: Stop and disable NetworkManager
  service:
    name: NetworkManager
    enabled: no

- name: Restart Network Service
  shell: reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: 192.168.10.{{ last_octect }}
    search_regex: OpenSSH
    delay: 10
  connection: local
